### ISSUE TITLE
compile error for Delphi 2009

### ISSUE THREAD

**Issue by r00xus** [graemeg/tiopf#1]
[DCC Error] tiLogToFile.pas(77): E2003 Undeclared identifier: 'Start'

class TtiThrdLog does not contain method Start

**Comment by graemeg** [comment]
Which branch of tiOPF are you trying to compile? Using Delphi 2009, you should be using the **tiopf3** branch - no other tiOPF branch is supported. TtiThrdLog is a distant TThread descendant, and the Start() method comes from the RTL's TThread class.

**Comment by r00xus** [comment]
I'm trying to compile tiopf3 with Delphi2009. Error occurs when compiling tiOPFCore2009.bpl tiOPFCore2009.bpl. And ther is no method Start in TThread class. I checked it out. This is a screenshot of the error
![error_screenshot](https://cloud.githubusercontent.com/assets/10000542/16113088/4dd437ae-33c3-11e6-8eee-849aa8914577.png)
May be I have to install some Update packages for Delphi2009?

**Comment by graemeg** [comment]
OK, I downloaded Delphi 2009's VCL help, and indeed, the Start() method was only introduced in Delphi 2010, and that is also when Resume() was marked as deprecated. As a work-around for you, please change line 77 to read: **ThrdLog.Resume;**
That should get you going again. I'll then create a fix with a correct IFDEF for that call.

**Comment by r00xus** [comment]
I replaced the line calling the Start method on the method Resume. But there are new errors:
[DCC Error] tiSmartPointer.pas(137): E2361 Cannot access private symbol RtiSmartPointer<T>.FPointer
[DCC Error] tiSmartPointer.pas(142): E2361 Cannot access private symbol RtiSmartPointer<T>.FPointer

**Comment by graemeg** [comment]
Please get another repository update and try again. I applied a few commits which should hopefully help. As I mentioned I don't have D2009 to test with, so I rely solely on your feedback. If you want, also take a look at the commit log (gitk is a useful tool) to see what changed. You should now be able to revert your ThrdLog.Resume() changes too.

**Comment by graemeg** [comment]
No further comments received, so I assume my changes resolved the problem.
