### ISSUE TITLE
The file tiDefines.inc not loaded

### ISSUE THREAD

**Issue by jacksondeveloper** [graemeg/tiopf#2]
I'm trying to use tiopf2 with Lazarus 1.6.4 and windows 10.

When creating a new project and import the units: tiOPFManager, tiQuerySqldbPQ I receive the error:

TiQuerySqldbPQ.pas (15,2) Fatal: Can not open include file "tiDefines.inc"

To resolve this temporarily I change:

{$ I tiDefines.inc}

To:

{$ I ../Core/tiDefines.inc}

On two units: tiQuerySqldb and tiQueryDataset

**Comment by graemeg** [comment]
It is not a bug, but in how you have set up the compiler environment for your current project. With Lazarus it is recommended to use the included Lazarus Packages found in < tiopf >/Compiler/FPC/ directory. Simply open them once so Lazarus knows about them. Then in your project's Project Inspector, add the tiopf.lpk package dependency. All tiOPF units and include files will then be found. For more details please see the Lazarus Wiki page: http://wiki.freepascal.org/tiOPF

If you don't want to use Lazarus Packages (I'm not a big fan of them), then you need to set up the correct Unit and Include search paths in your Compiler Options. If you create many tiOPF based projects, I recommend you create a project template to help save you some time. The compiler settings will look something like the following (replace the path to tiOPF to match your system):
```
 -Fi/data/devel/tiopf/Core
 -Fu/data/devel/tiopf/Core
 -Fu/data/devel/tiopf/Options
 -Fu/data/devel/tiopf/GUI/LCL
```

**Comment by jacksondeveloper** [comment]
I already did that. 

But now, I added: 

`tiopf-tiopf2\Compilers\FPC\lib\x86_64-win64\`

and it's working now. Thanks.

Sorry my English, I'm from Brasil.
